# Generated by Django 4.0.3 on 2022-04-09 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mascota', models.CharField(max_length=60)),
                ('sexo', models.CharField(max_length=1)),
                ('especie', models.CharField(max_length=60)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='micuenta.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='micuenta.mascota')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='micuenta.perfil')),
            ],
        ),
    ]
